### ISSUE TITLE
No examples or libraries to convert mainstream data to TimeStream

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [awslabs/amazon-timestream-tools#57]
Hello,

The CRUD sample is sending data that is constructed by hand. Do we have any automated way of building of payload without we building the payload. Cant this be automatically done without users defining the data in this format ? 

    const cpuUtilization = {
        'Dimensions': dimensions,
        'MeasureName': 'cpu_utilization',
        'MeasureValue': '13.5',
        'MeasureValueType': 'DOUBLE',
        'Time': currentTime.toString()
    };

    const memoryUtilization = {
        'Dimensions': dimensions,
        'MeasureName': 'memory_utilization',
        'MeasureValue': '40',
        'MeasureValueType': 'DOUBLE',
        'Time': currentTime.toString()
    };

**Comment by alexey-temnikov** [comment]
Hi @IrfanSyed-PSC,

Could you please provide more information about the specific scenarios you have in mind for automation? Additionally, sharing your use case will help us better understand your requirements and enable us to propose the most suitable solution.

I understand that this ticket was raised quite some time ago. If it is no longer relevant or if you have found a solution, please let us know so that we can close this issue appropriately.

**Comment by IrfanSyed-PSC** [comment]
We are not longer using it, so no update on that. Will close the ticket.
